version: 0.2

env:
  variables:
    CODEARTIFACT_DOMAIN: "vamsi"
    CODEARTIFACT_REPO: "pypi-store"
    REGION: "ap-south-1"
    EC2_PUBLIC_IP: "3.110.55.7"
    EC2_USER: "ubuntu"
    PARAM_NAME: "vamsi-parameter"
    PACKAGE_NAME: "my-python-app"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip build twine

  pre_build:
    commands:
      - echo "Authenticating to CodeArtifact..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export ACCOUNT_ID
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain $CODEARTIFACT_DOMAIN \
          --region $REGION \
          --query authorizationToken --output text)

  build:
    commands:
      - echo "Building Python package..."
      - python -m build

  post_build:
    commands:
      - echo "Uploading to CodeArtifact..."
      - |
        twine upload \
          --repository-url https://$CODEARTIFACT_DOMAIN-$ACCOUNT_ID.d.codeartifact.$REGION.amazonaws.com/pypi/$CODEARTIFACT_REPO/ \
          -u aws \
          -p $CODEARTIFACT_AUTH_TOKEN \
          dist/*

      - echo "Fetching SSH key from Parameter Store..."
      - aws ssm get-parameter \
          --name "$PARAM_NAME" \
          --with-decryption \
          --query Parameter.Value \
          --output text > key.pem
      - chmod 400 key.pem

      - echo "Deploying to EC2..."
      - |
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_PUBLIC_IP << 'EOF'
          echo "Getting CodeArtifact token..."
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain vamsi \
            --region ap-south-1 \
            --query authorizationToken --output text)

          echo "Installing package from CodeArtifact..."
          pip install --upgrade my-python-app \
            --extra-index-url https://vamsi-$ACCOUNT_ID.d.codeartifact.ap-south-1.amazonaws.com/pypi/vamsi-repository/simple/
        EOF
