version: 0.2

env:
  variables:
    CODEARTIFACT_DOMAIN: "my-domain"
    CODEARTIFACT_REPO: "my-python-repo"
    REGION: "ap-south-1"
    PACKAGE_NAME: "my-python-app"
    PARAM_INSTANCE_ID: "/prod/ec2/my-python-app-id"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip build twine
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain $CODEARTIFACT_DOMAIN --region $REGION \
          --query authorizationToken --output text)
  build:
    commands:
      - python -m build
  post_build:
    commands:
      - echo "Uploading to CodeArtifact..."
      - twine upload --repository-url https://$CODEARTIFACT_DOMAIN-$ACCOUNT_ID.d.codeartifact.$REGION.amazonaws.com/pypi/$CODEARTIFACT_REPO/ \
          -u aws -p $CODEARTIFACT_AUTH_TOKEN dist/*
      - echo "Fetching EC2 Instance ID from SSM..."
      - INSTANCE_ID=$(aws ssm get-parameter --name "$PARAM_INSTANCE_ID" --query "Parameter.Value" --output text)
      - echo "Sending install command to EC2 via SSM..."
      - aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --region $REGION \
          --instance-ids "$INSTANCE_ID" \
          --comment "Install and run $PACKAGE_NAME from CodeArtifact" \
          --parameters 'commands=[
            "sudo apt update && sudo apt install -y python3-pip unzip curl",
            "curl \\"https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip\\" -o \\"awscliv2.zip\\"",
            "unzip awscliv2.zip && sudo ./aws/install",
            "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)",
            "export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain '$CODEARTIFACT_DOMAIN' --region '$REGION' --query authorizationToken --output text)",
            "pip install --upgrade '$PACKAGE_NAME' --extra-index-url https://'$CODEARTIFACT_DOMAIN'-'$ACCOUNT_ID'.d.codeartifact.'$REGION'.amazonaws.com/pypi/'$CODEARTIFACT_REPO'/simple/",
            "myapp"
          ]'

artifacts:
  files:
    - dist/*.whl
    - dist/*.tar.gz
